### ISSUE TITLE
infografia  gilberto velasco osorio 

### ISSUE THREAD

**Issue by gilbertovelasco1** [SistemasTecTlaxiaco/actividad-2-infografia-gilbertovelasco1#1]
[infografía Gilberto Velasco.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-gilbertovelasco1/files/9465338/infografia.Gilberto.Velasco.pdf)

**Comment by MarleneRamirez0731** [comment]
18% de 20

**Comment by josealfredo79** [comment]
Se debe calificar bien @MarleneRamirez0731

**Comment by josealfredo79** [comment]
Se debe complementar correctamente...el trabajo realizado...

**Comment by josealfredo79** [comment]
Falta las referencias....

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica tiene 13%

**Comment by gilbertovelasco1** [comment]
[Infografía gilberto velasco osorio1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-gilbertovelasco1/files/9523491/Infografia.gilberto.velasco.osorio1.pdf)
Nueva infografía Gilberto Velasco Osorio

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rubrica tiene un 18 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
